### PR TITLE
Improvements on the python code

### PR DESCRIPTION
**Pull request by Berkmann18**
The improvements I made where the following
- Slight reduction of the running time of the initial parts of the code
- Added edge case handlers for "" or any invalid SSID
- Added the support for multiple arguments to allow the user to select not one, not all but a few wifi only
- Added the programless support allowing an easier usage of the script

The only thing missing is the gifs to make (that would obviously need to match the current ones) for the multi-arg section

### CODE REVIEW

**Comment by JeeveshN** [comment]
Seems like you broke something.
And i would suggest not to change any variable names that I had used earlier.
capture

**Comment by Berkmann18** [comment]
@JeeveshN On my pc it flags up wrong SSID correctly tho. At least on my Linux distro and on my Windows terminal
passpy

**Comment by JeeveshN** [comment]
@Berkmann18 and you've made the code slower for windows by changing the implementation for password retrieval in case of single wifi name.
I don't want it to support multiple arguments as that makes the code much slower because ```SAVED_PASSWORD``` dict takes a lot more time to get populated than the ```get_pass_individual()``` function.

**Comment by Berkmann18** [comment]
@JeeveshN Okay, so I suppose you don't need my improvements (which takes effect on Linux) ?

**Comment by JeeveshN** [comment]
@Berkmann18 I don't mind adding them as long as they don't slow up the script on any of the platform.
Windows part of the script is the most important one, I don't want to compromise in that part.
If you can find a faster way for your suggested functionality I'll be glad to accept this PR.

**Comment by Berkmann18** [comment]
Okay.

**Pull request closed without merging**
